### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by MedivhGO** [tang-jiapeng/AP1400-2-HW3#1]
1. 确实单元测试是需要寻找前驱节点
2. BST的重载赋值运算符需要将原有的BST结构析构掉
3. 你的 delete_node 实现好像过不了 TEST22，可能是单元测试的问题？

**Comment by tang-jiapeng** [comment]
@MedivhGO 应该是的，但当时没有重写单元测试，也不确定有没有问题

**Comment by MedivhGO** [comment]
我在可视化网站上走了一遍流程，测试好像没问题。

**Comment by tang-jiapeng** [comment]
@MedivhGO 
我用三个可视化网站模拟了TEST22
https://visualgo.net/zh/bst
http://www.rmboot.com/BST.html
http://520it.com/binarytrees/
但这三个网站的删除10后的BST却不一样分别如下：
![image](https://user-images.githubusercontent.com/83797617/213868607-58bd8802-2bdc-409b-b816-72b719c29a09.png)
![image](https://user-images.githubusercontent.com/83797617/213868615-d16e9407-a9b6-48ae-b58d-5fc8fd1740aa.png)
![image](https://user-images.githubusercontent.com/83797617/213868623-ea221ed8-7582-4b94-b9e4-9d5d174a1e01.png)
你应该是使用的第二个网站
BST的删除节点可以通过找前驱也可以找后继，我猜测是因为这个原因？
